# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hackgician
tagline:          'blog'
description:      'Just a blog made by <a href="https://twitter.com/hackgician" target="_blank">Andy Kamath</a>.'
url:              http://andykamath.com
baseurl:          /

author:
  name:           'Andy Kamath'
  url:            https://twitter.com/hackgician

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/hackgician/hackgician.github.io
